#
# Generated Makefile for PyQt interfaces
#
# Created on Fri Aug 11 20:35:51 2017

PYUIC=pyuic5
PYRCC=pyrcc5all:	ui_yindscaleoffdlg.py\
	ui_yscaleoffdlg.py\
	ui_xrvdlg.py\
	ui_progoptsdlg.py\
	ui_sdadminmain.py\
	ui_rangeseldlg.py\
	ui_newrangedlg.py\
	ui_xindhvdlg.py\
	ui_obsfileseldlg.py\
	sdares_rc.py

ui_yindscaleoffdlg.py:	yindscaleoffdlg.ui
	$(PYUIC) -o $@ $?

ui_yscaleoffdlg.py:	yscaleoffdlg.ui
	$(PYUIC) -o $@ $?

ui_xrvdlg.py:	xrvdlg.ui
	$(PYUIC) -o $@ $?

ui_progoptsdlg.py:	progoptsdlg.ui
	$(PYUIC) -o $@ $?

ui_sdadminmain.py:	sdadminmain.ui
	$(PYUIC) -o $@ $?

ui_rangeseldlg.py:	rangeseldlg.ui
	$(PYUIC) -o $@ $?

ui_newrangedlg.py:	newrangedlg.ui
	$(PYUIC) -o $@ $?

ui_xindhvdlg.py:	xindhvdlg.ui
	$(PYUIC) -o $@ $?

ui_obsfileseldlg.py:	obsfileseldlg.ui
	$(PYUIC) -o $@ $?

sdares_rc.py:	sdares.qrc
	$(PYRCC) -o $@ $?

clean:
	rm -f ui_*.py *_rc.py *.pyc

distclean: clean
	rm -f config.py
