#
# Generated Makefile for PyQt interfaces
#
# Created on Thu Jul  2 12:01:35 2015

all:	ui_rangeseldlg.py\
	ui_sdadminmain.py\
	ui_xrvdlg.py\
	ui_yindscaleoffdlg.py\
	ui_yscaleoffdlg.py\
	ui_newrangedlg.py\
	ui_xindhvdlg.py\
	ui_progoptsdlg.py\
	ui_obsfileseldlg.py\
	sdares_rc.py

ui_rangeseldlg.py:	rangeseldlg.ui
	pyuic4 -o $@ $?

ui_sdadminmain.py:	sdadminmain.ui
	pyuic4 -o $@ $?

ui_xrvdlg.py:	xrvdlg.ui
	pyuic4 -o $@ $?

ui_yindscaleoffdlg.py:	yindscaleoffdlg.ui
	pyuic4 -o $@ $?

ui_yscaleoffdlg.py:	yscaleoffdlg.ui
	pyuic4 -o $@ $?

ui_newrangedlg.py:	newrangedlg.ui
	pyuic4 -o $@ $?

ui_xindhvdlg.py:	xindhvdlg.ui
	pyuic4 -o $@ $?

ui_progoptsdlg.py:	progoptsdlg.ui
	pyuic4 -o $@ $?

ui_obsfileseldlg.py:	obsfileseldlg.ui
	pyuic4 -o $@ $?

sdares_rc.py:	sdares.qrc
	pyrcc4 -o $@ $?

clean:
	rm -f ui_*.py *_rc.py *.pyc

distclean: clean
	rm -f config.py
