#
# Generated Makefile for PyQt interfaces
#
# Created on Sun Jun 21 23:33:40 2015

all:	ui_yindscaleoffdlg.py\
	ui_yscaleoffdlg.py\
	ui_progoptsdlg.py\
	ui_sdadminmain.py\
	ui_rangeseldlg.py\
	ui_newrangedlg.py\
	ui_xindscaleoffdlg.py\
	ui_obsfileseldlg.py\
	ui_xscaleoffdlg.py\
	sdares_rc.py

ui_yindscaleoffdlg.py:	yindscaleoffdlg.ui
	pyuic4 -o $@ $?

ui_yscaleoffdlg.py:	yscaleoffdlg.ui
	pyuic4 -o $@ $?

ui_progoptsdlg.py:	progoptsdlg.ui
	pyuic4 -o $@ $?

ui_sdadminmain.py:	sdadminmain.ui
	pyuic4 -o $@ $?

ui_rangeseldlg.py:	rangeseldlg.ui
	pyuic4 -o $@ $?

ui_newrangedlg.py:	newrangedlg.ui
	pyuic4 -o $@ $?

ui_xindscaleoffdlg.py:	xindscaleoffdlg.ui
	pyuic4 -o $@ $?

ui_obsfileseldlg.py:	obsfileseldlg.ui
	pyuic4 -o $@ $?

ui_xscaleoffdlg.py:	xscaleoffdlg.ui
	pyuic4 -o $@ $?

sdares_rc.py:	sdares.qrc
	pyrcc4 -o $@ $?

clean:
	rm -f ui_*.py *_rc.py *.pyc

distclean: clean
	rm -f config.py
