# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newrangedlg.ui'
#
# Created: Wed Mar 19 11:03:51 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_newrangedlg(object):
    def setupUi(self, newrangedlg):
        newrangedlg.setObjectName("newrangedlg")
        newrangedlg.resize(787, 312)
        self.buttonBox = QtGui.QDialogButtonBox(newrangedlg)
        self.buttonBox.setGeometry(QtCore.QRect(520, 270, 221, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(newrangedlg)
        self.label.setGeometry(QtCore.QRect(40, 30, 101, 17))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(newrangedlg)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 91, 17))
        self.label_2.setObjectName("label_2")
        self.selcolour = QtGui.QPushButton(newrangedlg)
        self.selcolour.setGeometry(QtCore.QRect(40, 200, 121, 27))
        self.selcolour.setObjectName("selcolour")
        self.colourdisp = QtGui.QGraphicsView(newrangedlg)
        self.colourdisp.setGeometry(QtCore.QRect(210, 180, 151, 61))
        self.colourdisp.setObjectName("colourdisp")
        self.rinuse = QtGui.QCheckBox(newrangedlg)
        self.rinuse.setGeometry(QtCore.QRect(530, 210, 93, 22))
        self.rinuse.setObjectName("rinuse")
        self.shortname = QtGui.QLineEdit(newrangedlg)
        self.shortname.setGeometry(QtCore.QRect(200, 70, 191, 27))
        self.shortname.setObjectName("shortname")
        self.rangename = QtGui.QLineEdit(newrangedlg)
        self.rangename.setGeometry(QtCore.QRect(200, 30, 541, 27))
        self.rangename.setObjectName("rangename")
        self.srump1 = QtGui.QPushButton(newrangedlg)
        self.srump1.setGeometry(QtCore.QRect(430, 140, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srump1.setFont(font)
        self.srump1.setAutoRepeat(True)
        self.srump1.setObjectName("srump1")
        self.srbpp1 = QtGui.QPushButton(newrangedlg)
        self.srbpp1.setGeometry(QtCore.QRect(540, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbpp1.setFont(font)
        self.srbpp1.setAutoRepeat(True)
        self.srbpp1.setObjectName("srbpp1")
        self.srupp1 = QtGui.QPushButton(newrangedlg)
        self.srupp1.setGeometry(QtCore.QRect(430, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srupp1.setFont(font)
        self.srupp1.setAutoRepeat(True)
        self.srupp1.setObjectName("srupp1")
        self.label_9 = QtGui.QLabel(newrangedlg)
        self.label_9.setGeometry(QtCore.QRect(260, 130, 41, 17))
        self.label_9.setObjectName("label_9")
        self.srbmp5 = QtGui.QPushButton(newrangedlg)
        self.srbmp5.setGeometry(QtCore.QRect(570, 140, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbmp5.setFont(font)
        self.srbmp5.setAutoRepeat(True)
        self.srbmp5.setObjectName("srbmp5")
        self.srupp5 = QtGui.QPushButton(newrangedlg)
        self.srupp5.setGeometry(QtCore.QRect(460, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srupp5.setFont(font)
        self.srupp5.setAutoRepeat(True)
        self.srupp5.setObjectName("srupp5")
        self.srump5 = QtGui.QPushButton(newrangedlg)
        self.srump5.setGeometry(QtCore.QRect(460, 141, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srump5.setFont(font)
        self.srump5.setAutoRepeat(True)
        self.srump5.setObjectName("srump5")
        self.srlmp1 = QtGui.QPushButton(newrangedlg)
        self.srlmp1.setGeometry(QtCore.QRect(170, 140, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlmp1.setFont(font)
        self.srlmp1.setAutoRepeat(True)
        self.srlmp1.setObjectName("srlmp1")
        self.srlpp5 = QtGui.QPushButton(newrangedlg)
        self.srlpp5.setGeometry(QtCore.QRect(200, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlpp5.setFont(font)
        self.srlpp5.setAutoRepeat(True)
        self.srlpp5.setObjectName("srlpp5")
        self.srmax = QtGui.QDoubleSpinBox(newrangedlg)
        self.srmax.setGeometry(QtCore.QRect(310, 130, 91, 27))
        self.srmax.setDecimals(3)
        self.srmax.setMinimum(6500.0)
        self.srmax.setMaximum(6650.0)
        self.srmax.setSingleStep(0.01)
        self.srmax.setProperty("value", 6600.0)
        self.srmax.setObjectName("srmax")
        self.srbmp1 = QtGui.QPushButton(newrangedlg)
        self.srbmp1.setGeometry(QtCore.QRect(540, 140, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbmp1.setFont(font)
        self.srbmp1.setAutoRepeat(True)
        self.srbmp1.setObjectName("srbmp1")
        self.srbpp5 = QtGui.QPushButton(newrangedlg)
        self.srbpp5.setGeometry(QtCore.QRect(570, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbpp5.setFont(font)
        self.srbpp5.setAutoRepeat(True)
        self.srbpp5.setObjectName("srbpp5")
        self.srlpp1 = QtGui.QPushButton(newrangedlg)
        self.srlpp1.setGeometry(QtCore.QRect(170, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlpp1.setFont(font)
        self.srlpp1.setAutoRepeat(True)
        self.srlpp1.setObjectName("srlpp1")
        self.srmin = QtGui.QDoubleSpinBox(newrangedlg)
        self.srmin.setGeometry(QtCore.QRect(40, 130, 91, 27))
        self.srmin.setDecimals(3)
        self.srmin.setMinimum(6500.0)
        self.srmin.setMaximum(6650.0)
        self.srmin.setSingleStep(0.01)
        self.srmin.setProperty("value", 6530.0)
        self.srmin.setObjectName("srmin")
        self.srlmp5 = QtGui.QPushButton(newrangedlg)
        self.srlmp5.setGeometry(QtCore.QRect(200, 140, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlmp5.setFont(font)
        self.srlmp5.setAutoRepeat(True)
        self.srlmp5.setObjectName("srlmp5")

        self.retranslateUi(newrangedlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), newrangedlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), newrangedlg.reject)
        QtCore.QMetaObject.connectSlotsByName(newrangedlg)
        newrangedlg.setTabOrder(self.rangename, self.shortname)
        newrangedlg.setTabOrder(self.shortname, self.srmin)
        newrangedlg.setTabOrder(self.srmin, self.srlpp1)
        newrangedlg.setTabOrder(self.srlpp1, self.srlpp5)
        newrangedlg.setTabOrder(self.srlpp5, self.srlmp1)
        newrangedlg.setTabOrder(self.srlmp1, self.srlmp5)
        newrangedlg.setTabOrder(self.srlmp5, self.srmax)
        newrangedlg.setTabOrder(self.srmax, self.srupp1)
        newrangedlg.setTabOrder(self.srupp1, self.srupp5)
        newrangedlg.setTabOrder(self.srupp5, self.srump1)
        newrangedlg.setTabOrder(self.srump1, self.srump5)
        newrangedlg.setTabOrder(self.srump5, self.srbpp1)
        newrangedlg.setTabOrder(self.srbpp1, self.srbpp5)
        newrangedlg.setTabOrder(self.srbpp5, self.srbmp1)
        newrangedlg.setTabOrder(self.srbmp1, self.srbmp5)
        newrangedlg.setTabOrder(self.srbmp5, self.selcolour)
        newrangedlg.setTabOrder(self.selcolour, self.colourdisp)
        newrangedlg.setTabOrder(self.colourdisp, self.rinuse)
        newrangedlg.setTabOrder(self.rinuse, self.buttonBox)

    def retranslateUi(self, newrangedlg):
        newrangedlg.setWindowTitle(QtGui.QApplication.translate("newrangedlg", "Create new range", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("newrangedlg", "Range Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("newrangedlg", "Short Name", None, QtGui.QApplication.UnicodeUTF8))
        self.selcolour.setToolTip(QtGui.QApplication.translate("newrangedlg", "Select colour on display", None, QtGui.QApplication.UnicodeUTF8))
        self.selcolour.setText(QtGui.QApplication.translate("newrangedlg", "Choose Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.rinuse.setToolTip(QtGui.QApplication.translate("newrangedlg", "Range is in use", None, QtGui.QApplication.UnicodeUTF8))
        self.rinuse.setText(QtGui.QApplication.translate("newrangedlg", "In use", None, QtGui.QApplication.UnicodeUTF8))
        self.shortname.setToolTip(QtGui.QApplication.translate("newrangedlg", "Short name for the range", None, QtGui.QApplication.UnicodeUTF8))
        self.rangename.setToolTip(QtGui.QApplication.translate("newrangedlg", "Full name for the range", None, QtGui.QApplication.UnicodeUTF8))
        self.srump1.setToolTip(QtGui.QApplication.translate("newrangedlg", "Subtract 0.1 from range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srump1.setText(QtGui.QApplication.translate("newrangedlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp1.setToolTip(QtGui.QApplication.translate("newrangedlg", "Expand ends of range by .1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp1.setText(QtGui.QApplication.translate("newrangedlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp1.setToolTip(QtGui.QApplication.translate("newrangedlg", "Add 0.1 to range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp1.setText(QtGui.QApplication.translate("newrangedlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("newrangedlg", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp5.setToolTip(QtGui.QApplication.translate("newrangedlg", "Contract ends of range by .5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp5.setText(QtGui.QApplication.translate("newrangedlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp5.setToolTip(QtGui.QApplication.translate("newrangedlg", "Add 0.5 to range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp5.setText(QtGui.QApplication.translate("newrangedlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srump5.setToolTip(QtGui.QApplication.translate("newrangedlg", "Subtract 0.5 from range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srump5.setText(QtGui.QApplication.translate("newrangedlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp1.setToolTip(QtGui.QApplication.translate("newrangedlg", "Subtract 0.1 from range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp1.setText(QtGui.QApplication.translate("newrangedlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp5.setToolTip(QtGui.QApplication.translate("newrangedlg", "Add 0.5 to range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp5.setText(QtGui.QApplication.translate("newrangedlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srmax.setToolTip(QtGui.QApplication.translate("newrangedlg", "This is the upper bound of the range.", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp1.setToolTip(QtGui.QApplication.translate("newrangedlg", "Contract ends of range by .1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp1.setText(QtGui.QApplication.translate("newrangedlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp5.setToolTip(QtGui.QApplication.translate("newrangedlg", "Expand ends of range by .5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp5.setText(QtGui.QApplication.translate("newrangedlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp1.setToolTip(QtGui.QApplication.translate("newrangedlg", "Add 0.1 to range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp1.setText(QtGui.QApplication.translate("newrangedlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srmin.setToolTip(QtGui.QApplication.translate("newrangedlg", "This is the lower bound of the range", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp5.setToolTip(QtGui.QApplication.translate("newrangedlg", "Subtract 0.5 from range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp5.setText(QtGui.QApplication.translate("newrangedlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))

