# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obsfileseldlg.ui'
#
# Created: Wed Mar 19 11:03:51 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_obsfileseldlg(object):
    def setupUi(self, obsfileseldlg):
        obsfileseldlg.setObjectName("obsfileseldlg")
        obsfileseldlg.resize(994, 633)
        self.buttonBox = QtGui.QDialogButtonBox(obsfileseldlg)
        self.buttonBox.setGeometry(QtCore.QRect(740, 560, 211, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(obsfileseldlg)
        self.label.setGeometry(QtCore.QRect(30, 40, 221, 17))
        self.label.setObjectName("label")
        self.obsfile = QtGui.QLineEdit(obsfileseldlg)
        self.obsfile.setGeometry(QtCore.QRect(250, 30, 681, 27))
        self.obsfile.setObjectName("obsfile")
        self.selobsfile = QtGui.QPushButton(obsfileseldlg)
        self.selobsfile.setGeometry(QtCore.QRect(790, 70, 141, 27))
        self.selobsfile.setObjectName("selobsfile")
        self.obsfields = QtGui.QListWidget(obsfileseldlg)
        self.obsfields.setGeometry(QtCore.QRect(250, 90, 256, 192))
        self.obsfields.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.obsfields.setObjectName("obsfields")
        self.addobsfield = QtGui.QPushButton(obsfileseldlg)
        self.addobsfield.setGeometry(QtCore.QRect(540, 140, 92, 27))
        self.addobsfield.setObjectName("addobsfield")
        self.delobsfield = QtGui.QPushButton(obsfileseldlg)
        self.delobsfield.setGeometry(QtCore.QRect(540, 190, 92, 27))
        self.delobsfield.setObjectName("delobsfield")
        self.label_2 = QtGui.QLabel(obsfileseldlg)
        self.label_2.setGeometry(QtCore.QRect(40, 170, 101, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(obsfileseldlg)
        self.label_3.setGeometry(QtCore.QRect(40, 420, 121, 17))
        self.label_3.setObjectName("label_3")
        self.delspecfield = QtGui.QPushButton(obsfileseldlg)
        self.delspecfield.setGeometry(QtCore.QRect(540, 440, 92, 27))
        self.delspecfield.setObjectName("delspecfield")
        self.addspecfield = QtGui.QPushButton(obsfileseldlg)
        self.addspecfield.setGeometry(QtCore.QRect(540, 390, 92, 27))
        self.addspecfield.setObjectName("addspecfield")
        self.specfields = QtGui.QListWidget(obsfileseldlg)
        self.specfields.setGeometry(QtCore.QRect(250, 340, 256, 192))
        self.specfields.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.specfields.setObjectName("specfields")
        self.selobsfield = QtGui.QComboBox(obsfileseldlg)
        self.selobsfield.setGeometry(QtCore.QRect(680, 140, 241, 27))
        self.selobsfield.setObjectName("selobsfield")
        self.selspecfield = QtGui.QComboBox(obsfileseldlg)
        self.selspecfield.setGeometry(QtCore.QRect(670, 390, 241, 27))
        self.selspecfield.setObjectName("selspecfield")

        self.retranslateUi(obsfileseldlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), obsfileseldlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), obsfileseldlg.reject)
        QtCore.QMetaObject.connectSlotsByName(obsfileseldlg)
        obsfileseldlg.setTabOrder(self.obsfile, self.selobsfile)
        obsfileseldlg.setTabOrder(self.selobsfile, self.obsfields)
        obsfileseldlg.setTabOrder(self.obsfields, self.addobsfield)
        obsfileseldlg.setTabOrder(self.addobsfield, self.delobsfield)
        obsfileseldlg.setTabOrder(self.delobsfield, self.selobsfield)
        obsfileseldlg.setTabOrder(self.selobsfield, self.specfields)
        obsfileseldlg.setTabOrder(self.specfields, self.addspecfield)
        obsfileseldlg.setTabOrder(self.addspecfield, self.delspecfield)
        obsfileseldlg.setTabOrder(self.delspecfield, self.selspecfield)
        obsfileseldlg.setTabOrder(self.selspecfield, self.buttonBox)

    def retranslateUi(self, obsfileseldlg):
        obsfileseldlg.setWindowTitle(QtGui.QApplication.translate("obsfileseldlg", "Select file/directory and fields", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("obsfileseldlg", "Observation file directory/path", None, QtGui.QApplication.UnicodeUTF8))
        self.obsfile.setToolTip(QtGui.QApplication.translate("obsfileseldlg", "This is the file name (with directory) giving the observation\n"
"times, possibly the file names", None, QtGui.QApplication.UnicodeUTF8))
        self.selobsfile.setToolTip(QtGui.QApplication.translate("obsfileseldlg", "Click to select observation file", None, QtGui.QApplication.UnicodeUTF8))
        self.selobsfile.setText(QtGui.QApplication.translate("obsfileseldlg", "Select obs file", None, QtGui.QApplication.UnicodeUTF8))
        self.obsfields.setToolTip(QtGui.QApplication.translate("obsfileseldlg", "This is the columns in order of the obs file fields", None, QtGui.QApplication.UnicodeUTF8))
        self.addobsfield.setToolTip(QtGui.QApplication.translate("obsfileseldlg", "Click to add the selected field", None, QtGui.QApplication.UnicodeUTF8))
        self.addobsfield.setText(QtGui.QApplication.translate("obsfileseldlg", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.delobsfield.setToolTip(QtGui.QApplication.translate("obsfileseldlg", "Click to delete the selected field", None, QtGui.QApplication.UnicodeUTF8))
        self.delobsfield.setText(QtGui.QApplication.translate("obsfileseldlg", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("obsfileseldlg", "Obs file fields", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("obsfileseldlg", "Spectral file fields", None, QtGui.QApplication.UnicodeUTF8))
        self.delspecfield.setToolTip(QtGui.QApplication.translate("obsfileseldlg", "Click to delete the selected field", None, QtGui.QApplication.UnicodeUTF8))
        self.delspecfield.setText(QtGui.QApplication.translate("obsfileseldlg", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.addspecfield.setToolTip(QtGui.QApplication.translate("obsfileseldlg", "Click to add the selected field", None, QtGui.QApplication.UnicodeUTF8))
        self.addspecfield.setText(QtGui.QApplication.translate("obsfileseldlg", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.specfields.setToolTip(QtGui.QApplication.translate("obsfileseldlg", "These are the columns in order of the fields in the spectral file.", None, QtGui.QApplication.UnicodeUTF8))
        self.selobsfield.setToolTip(QtGui.QApplication.translate("obsfileseldlg", "Possible obs file fields", None, QtGui.QApplication.UnicodeUTF8))
        self.selspecfield.setToolTip(QtGui.QApplication.translate("obsfileseldlg", "Possible spectrum file fields", None, QtGui.QApplication.UnicodeUTF8))

