# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rangeseldlg.ui'
#
# Created: Wed Mar 19 11:03:51 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_rangeseldlg(object):
    def setupUi(self, rangeseldlg):
        rangeseldlg.setObjectName("rangeseldlg")
        rangeseldlg.resize(930, 629)
        self.buttonBox = QtGui.QDialogButtonBox(rangeseldlg)
        self.buttonBox.setGeometry(QtCore.QRect(740, 550, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(rangeseldlg)
        self.label.setGeometry(QtCore.QRect(70, 80, 101, 17))
        self.label.setObjectName("label")
        self.xrangemin = QtGui.QDoubleSpinBox(rangeseldlg)
        self.xrangemin.setGeometry(QtCore.QRect(280, 320, 91, 27))
        self.xrangemin.setDecimals(3)
        self.xrangemin.setMinimum(6500.0)
        self.xrangemin.setMaximum(6650.0)
        self.xrangemin.setSingleStep(0.01)
        self.xrangemin.setObjectName("xrangemin")
        self.label_3 = QtGui.QLabel(rangeseldlg)
        self.label_3.setGeometry(QtCore.QRect(500, 330, 41, 17))
        self.label_3.setObjectName("label_3")
        self.xrangemax = QtGui.QDoubleSpinBox(rangeseldlg)
        self.xrangemax.setGeometry(QtCore.QRect(550, 320, 91, 27))
        self.xrangemax.setDecimals(3)
        self.xrangemax.setMinimum(6500.0)
        self.xrangemax.setMaximum(6650.0)
        self.xrangemax.setSingleStep(0.01)
        self.xrangemax.setProperty("value", 6650.0)
        self.xrangemax.setObjectName("xrangemax")
        self.rlmp1 = QtGui.QPushButton(rangeseldlg)
        self.rlmp1.setGeometry(QtCore.QRect(410, 340, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlmp1.setFont(font)
        self.rlmp1.setAutoRepeat(True)
        self.rlmp1.setObjectName("rlmp1")
        self.rlmp5 = QtGui.QPushButton(rangeseldlg)
        self.rlmp5.setGeometry(QtCore.QRect(440, 340, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlmp5.setFont(font)
        self.rlmp5.setAutoRepeat(True)
        self.rlmp5.setObjectName("rlmp5")
        self.rlpp1 = QtGui.QPushButton(rangeseldlg)
        self.rlpp1.setGeometry(QtCore.QRect(410, 320, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlpp1.setFont(font)
        self.rlpp1.setAutoRepeat(True)
        self.rlpp1.setObjectName("rlpp1")
        self.rlpp5 = QtGui.QPushButton(rangeseldlg)
        self.rlpp5.setGeometry(QtCore.QRect(440, 320, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rlpp5.setFont(font)
        self.rlpp5.setAutoRepeat(True)
        self.rlpp5.setObjectName("rlpp5")
        self.rump1 = QtGui.QPushButton(rangeseldlg)
        self.rump1.setGeometry(QtCore.QRect(670, 340, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rump1.setFont(font)
        self.rump1.setAutoRepeat(True)
        self.rump1.setObjectName("rump1")
        self.rupp1 = QtGui.QPushButton(rangeseldlg)
        self.rupp1.setGeometry(QtCore.QRect(670, 320, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rupp1.setFont(font)
        self.rupp1.setAutoRepeat(True)
        self.rupp1.setObjectName("rupp1")
        self.rump5 = QtGui.QPushButton(rangeseldlg)
        self.rump5.setGeometry(QtCore.QRect(700, 340, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rump5.setFont(font)
        self.rump5.setAutoRepeat(True)
        self.rump5.setObjectName("rump5")
        self.rupp5 = QtGui.QPushButton(rangeseldlg)
        self.rupp5.setGeometry(QtCore.QRect(700, 320, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rupp5.setFont(font)
        self.rupp5.setAutoRepeat(True)
        self.rupp5.setObjectName("rupp5")
        self.yrangemin = QtGui.QDoubleSpinBox(rangeseldlg)
        self.yrangemin.setGeometry(QtCore.QRect(280, 260, 111, 27))
        self.yrangemin.setDecimals(6)
        self.yrangemin.setMinimum(0.0)
        self.yrangemin.setMaximum(2.0)
        self.yrangemin.setSingleStep(0.1)
        self.yrangemin.setObjectName("yrangemin")
        self.label_7 = QtGui.QLabel(rangeseldlg)
        self.label_7.setGeometry(QtCore.QRect(430, 260, 21, 17))
        self.label_7.setObjectName("label_7")
        self.yrangemax = QtGui.QDoubleSpinBox(rangeseldlg)
        self.yrangemax.setGeometry(QtCore.QRect(480, 260, 111, 27))
        self.yrangemax.setDecimals(6)
        self.yrangemax.setMinimum(1.0)
        self.yrangemax.setMaximum(3.0)
        self.yrangemax.setSingleStep(0.1)
        self.yrangemax.setProperty("value", 3.0)
        self.yrangemax.setObjectName("yrangemax")
        self.srlmp5 = QtGui.QPushButton(rangeseldlg)
        self.srlmp5.setGeometry(QtCore.QRect(340, 520, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlmp5.setFont(font)
        self.srlmp5.setAutoRepeat(True)
        self.srlmp5.setObjectName("srlmp5")
        self.srlpp1 = QtGui.QPushButton(rangeseldlg)
        self.srlpp1.setGeometry(QtCore.QRect(310, 500, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlpp1.setFont(font)
        self.srlpp1.setAutoRepeat(True)
        self.srlpp1.setObjectName("srlpp1")
        self.srlpp5 = QtGui.QPushButton(rangeseldlg)
        self.srlpp5.setGeometry(QtCore.QRect(340, 500, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlpp5.setFont(font)
        self.srlpp5.setAutoRepeat(True)
        self.srlpp5.setObjectName("srlpp5")
        self.bkintlab = QtGui.QLabel(rangeseldlg)
        self.bkintlab.setGeometry(QtCore.QRect(60, 400, 111, 17))
        self.bkintlab.setObjectName("bkintlab")
        self.srupp1 = QtGui.QPushButton(rangeseldlg)
        self.srupp1.setGeometry(QtCore.QRect(570, 500, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srupp1.setFont(font)
        self.srupp1.setAutoRepeat(True)
        self.srupp1.setObjectName("srupp1")
        self.label_9 = QtGui.QLabel(rangeseldlg)
        self.label_9.setGeometry(QtCore.QRect(400, 510, 41, 17))
        self.label_9.setObjectName("label_9")
        self.srupp5 = QtGui.QPushButton(rangeseldlg)
        self.srupp5.setGeometry(QtCore.QRect(600, 500, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srupp5.setFont(font)
        self.srupp5.setAutoRepeat(True)
        self.srupp5.setObjectName("srupp5")
        self.srlmp1 = QtGui.QPushButton(rangeseldlg)
        self.srlmp1.setGeometry(QtCore.QRect(310, 520, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srlmp1.setFont(font)
        self.srlmp1.setAutoRepeat(True)
        self.srlmp1.setObjectName("srlmp1")
        self.srump5 = QtGui.QPushButton(rangeseldlg)
        self.srump5.setGeometry(QtCore.QRect(600, 521, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srump5.setFont(font)
        self.srump5.setAutoRepeat(True)
        self.srump5.setObjectName("srump5")
        self.srump1 = QtGui.QPushButton(rangeseldlg)
        self.srump1.setGeometry(QtCore.QRect(570, 520, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srump1.setFont(font)
        self.srump1.setAutoRepeat(True)
        self.srump1.setObjectName("srump1")
        self.srmin = QtGui.QDoubleSpinBox(rangeseldlg)
        self.srmin.setGeometry(QtCore.QRect(180, 510, 91, 27))
        self.srmin.setDecimals(3)
        self.srmin.setMinimum(6500.0)
        self.srmin.setMaximum(6650.0)
        self.srmin.setSingleStep(0.01)
        self.srmin.setProperty("value", 6530.0)
        self.srmin.setObjectName("srmin")
        self.srmax = QtGui.QDoubleSpinBox(rangeseldlg)
        self.srmax.setGeometry(QtCore.QRect(450, 510, 91, 27))
        self.srmax.setDecimals(3)
        self.srmax.setMinimum(6500.0)
        self.srmax.setMaximum(6650.0)
        self.srmax.setSingleStep(0.01)
        self.srmax.setProperty("value", 6600.0)
        self.srmax.setObjectName("srmax")
        self.srbmp1 = QtGui.QPushButton(rangeseldlg)
        self.srbmp1.setGeometry(QtCore.QRect(680, 520, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbmp1.setFont(font)
        self.srbmp1.setAutoRepeat(True)
        self.srbmp1.setObjectName("srbmp1")
        self.rbmp5 = QtGui.QPushButton(rangeseldlg)
        self.rbmp5.setGeometry(QtCore.QRect(810, 340, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbmp5.setFont(font)
        self.rbmp5.setAutoRepeat(True)
        self.rbmp5.setObjectName("rbmp5")
        self.rbpp1 = QtGui.QPushButton(rangeseldlg)
        self.rbpp1.setGeometry(QtCore.QRect(780, 320, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbpp1.setFont(font)
        self.rbpp1.setAutoRepeat(True)
        self.rbpp1.setObjectName("rbpp1")
        self.srbpp1 = QtGui.QPushButton(rangeseldlg)
        self.srbpp1.setGeometry(QtCore.QRect(680, 500, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbpp1.setFont(font)
        self.srbpp1.setAutoRepeat(True)
        self.srbpp1.setObjectName("srbpp1")
        self.rbpp5 = QtGui.QPushButton(rangeseldlg)
        self.rbpp5.setGeometry(QtCore.QRect(810, 320, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbpp5.setFont(font)
        self.rbpp5.setAutoRepeat(True)
        self.rbpp5.setObjectName("rbpp5")
        self.srbpp5 = QtGui.QPushButton(rangeseldlg)
        self.srbpp5.setGeometry(QtCore.QRect(710, 500, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbpp5.setFont(font)
        self.srbpp5.setAutoRepeat(True)
        self.srbpp5.setObjectName("srbpp5")
        self.rbmp1 = QtGui.QPushButton(rangeseldlg)
        self.rbmp1.setGeometry(QtCore.QRect(780, 340, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.rbmp1.setFont(font)
        self.rbmp1.setAutoRepeat(True)
        self.rbmp1.setObjectName("rbmp1")
        self.srbmp5 = QtGui.QPushButton(rangeseldlg)
        self.srbmp5.setGeometry(QtCore.QRect(710, 520, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.srbmp5.setFont(font)
        self.srbmp5.setAutoRepeat(True)
        self.srbmp5.setObjectName("srbmp5")
        self.label_10 = QtGui.QLabel(rangeseldlg)
        self.label_10.setGeometry(QtCore.QRect(790, 280, 41, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.datafiles = QtGui.QListWidget(rangeseldlg)
        self.datafiles.setGeometry(QtCore.QRect(220, 20, 431, 192))
        self.datafiles.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.datafiles.setObjectName("datafiles")
        self.warningmsg = QtGui.QLabel(rangeseldlg)
        self.warningmsg.setGeometry(QtCore.QRect(60, 560, 591, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.warningmsg.setFont(font)
        self.warningmsg.setObjectName("warningmsg")
        self.editrange = QtGui.QComboBox(rangeseldlg)
        self.editrange.setGeometry(QtCore.QRect(200, 400, 411, 27))
        self.editrange.setObjectName("editrange")
        self.editrange.addItem("")
        self.selcolour = QtGui.QPushButton(rangeseldlg)
        self.selcolour.setGeometry(QtCore.QRect(630, 400, 121, 27))
        self.selcolour.setObjectName("selcolour")
        self.colourdisp = QtGui.QGraphicsView(rangeseldlg)
        self.colourdisp.setGeometry(QtCore.QRect(760, 380, 151, 61))
        self.colourdisp.setObjectName("colourdisp")
        self.label_2 = QtGui.QLabel(rangeseldlg)
        self.label_2.setGeometry(QtCore.QRect(60, 460, 141, 21))
        self.label_2.setObjectName("label_2")
        self.addnew = QtGui.QPushButton(rangeseldlg)
        self.addnew.setGeometry(QtCore.QRect(420, 460, 92, 27))
        self.addnew.setObjectName("addnew")
        self.shortname = QtGui.QLineEdit(rangeseldlg)
        self.shortname.setGeometry(QtCore.QRect(200, 460, 191, 27))
        self.shortname.setObjectName("shortname")
        self.delrange = QtGui.QPushButton(rangeseldlg)
        self.delrange.setGeometry(QtCore.QRect(550, 460, 92, 27))
        self.delrange.setObjectName("delrange")
        self.selecty = QtGui.QCheckBox(rangeseldlg)
        self.selecty.setGeometry(QtCore.QRect(60, 270, 141, 22))
        self.selecty.setObjectName("selecty")
        self.selectx = QtGui.QCheckBox(rangeseldlg)
        self.selectx.setGeometry(QtCore.QRect(60, 320, 131, 22))
        self.selectx.setObjectName("selectx")
        self.rinuse = QtGui.QCheckBox(rangeseldlg)
        self.rinuse.setGeometry(QtCore.QRect(680, 460, 93, 22))
        self.rinuse.setObjectName("rinuse")

        self.retranslateUi(rangeseldlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), rangeseldlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), rangeseldlg.reject)
        QtCore.QMetaObject.connectSlotsByName(rangeseldlg)
        rangeseldlg.setTabOrder(self.datafiles, self.selecty)
        rangeseldlg.setTabOrder(self.selecty, self.yrangemin)
        rangeseldlg.setTabOrder(self.yrangemin, self.yrangemax)
        rangeseldlg.setTabOrder(self.yrangemax, self.selectx)
        rangeseldlg.setTabOrder(self.selectx, self.xrangemin)
        rangeseldlg.setTabOrder(self.xrangemin, self.rlpp1)
        rangeseldlg.setTabOrder(self.rlpp1, self.rlpp5)
        rangeseldlg.setTabOrder(self.rlpp5, self.rlmp1)
        rangeseldlg.setTabOrder(self.rlmp1, self.rlmp5)
        rangeseldlg.setTabOrder(self.rlmp5, self.xrangemax)
        rangeseldlg.setTabOrder(self.xrangemax, self.rupp1)
        rangeseldlg.setTabOrder(self.rupp1, self.rupp5)
        rangeseldlg.setTabOrder(self.rupp5, self.rump1)
        rangeseldlg.setTabOrder(self.rump1, self.rump5)
        rangeseldlg.setTabOrder(self.rump5, self.rbpp1)
        rangeseldlg.setTabOrder(self.rbpp1, self.rbpp5)
        rangeseldlg.setTabOrder(self.rbpp5, self.rbmp1)
        rangeseldlg.setTabOrder(self.rbmp1, self.rbmp5)
        rangeseldlg.setTabOrder(self.rbmp5, self.editrange)
        rangeseldlg.setTabOrder(self.editrange, self.selcolour)
        rangeseldlg.setTabOrder(self.selcolour, self.colourdisp)
        rangeseldlg.setTabOrder(self.colourdisp, self.shortname)
        rangeseldlg.setTabOrder(self.shortname, self.addnew)
        rangeseldlg.setTabOrder(self.addnew, self.delrange)
        rangeseldlg.setTabOrder(self.delrange, self.rinuse)
        rangeseldlg.setTabOrder(self.rinuse, self.srmin)
        rangeseldlg.setTabOrder(self.srmin, self.srlpp1)
        rangeseldlg.setTabOrder(self.srlpp1, self.srlpp5)
        rangeseldlg.setTabOrder(self.srlpp5, self.srlmp1)
        rangeseldlg.setTabOrder(self.srlmp1, self.srlmp5)
        rangeseldlg.setTabOrder(self.srlmp5, self.srmax)
        rangeseldlg.setTabOrder(self.srmax, self.srupp1)
        rangeseldlg.setTabOrder(self.srupp1, self.srupp5)
        rangeseldlg.setTabOrder(self.srupp5, self.srump1)
        rangeseldlg.setTabOrder(self.srump1, self.srump5)
        rangeseldlg.setTabOrder(self.srump5, self.srbpp1)
        rangeseldlg.setTabOrder(self.srbpp1, self.srbpp5)
        rangeseldlg.setTabOrder(self.srbpp5, self.srbmp1)
        rangeseldlg.setTabOrder(self.srbmp1, self.srbmp5)
        rangeseldlg.setTabOrder(self.srbmp5, self.buttonBox)

    def retranslateUi(self, rangeseldlg):
        rangeseldlg.setWindowTitle(QtGui.QApplication.translate("rangeseldlg", "Configure ranges", None, QtGui.QApplication.UnicodeUTF8))
        rangeseldlg.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Select the colour of the display line", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("rangeseldlg", "Loading file(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.xrangemin.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Select minimum of range to display", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("rangeseldlg", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.xrangemax.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Select maximum of range to display", None, QtGui.QApplication.UnicodeUTF8))
        self.rlmp1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Subtract .1 from range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlmp1.setText(QtGui.QApplication.translate("rangeseldlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rlmp5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Subtract .5 from range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlmp5.setText(QtGui.QApplication.translate("rangeseldlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.rlpp1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Add .1 to range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlpp1.setText(QtGui.QApplication.translate("rangeseldlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rlpp5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Add .5 to range min", None, QtGui.QApplication.UnicodeUTF8))
        self.rlpp5.setText(QtGui.QApplication.translate("rangeseldlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.rump1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Subtract .1 from range max", None, QtGui.QApplication.UnicodeUTF8))
        self.rump1.setText(QtGui.QApplication.translate("rangeseldlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rupp1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Add .1 to range max", None, QtGui.QApplication.UnicodeUTF8))
        self.rupp1.setText(QtGui.QApplication.translate("rangeseldlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rump5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Subtract .5 from range max", None, QtGui.QApplication.UnicodeUTF8))
        self.rump5.setText(QtGui.QApplication.translate("rangeseldlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.rupp5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Add .5 to range max", None, QtGui.QApplication.UnicodeUTF8))
        self.rupp5.setText(QtGui.QApplication.translate("rangeseldlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.yrangemin.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Select bottom of Y range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("rangeseldlg", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.yrangemax.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Select maximum of Y range", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Subtract 0.5 from range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp5.setText(QtGui.QApplication.translate("rangeseldlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Add 0.1 to range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp1.setText(QtGui.QApplication.translate("rangeseldlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Add 0.5 to range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlpp5.setText(QtGui.QApplication.translate("rangeseldlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.bkintlab.setText(QtGui.QApplication.translate("rangeseldlg", "Range to edit", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Add 0.1 to range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp1.setText(QtGui.QApplication.translate("rangeseldlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("rangeseldlg", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Add 0.5 to range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srupp5.setText(QtGui.QApplication.translate("rangeseldlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Subtract 0.1 from range lower bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srlmp1.setText(QtGui.QApplication.translate("rangeseldlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srump5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Subtract 0.5 from range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srump5.setText(QtGui.QApplication.translate("rangeseldlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srump1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Subtract 0.1 from range upper bound.", None, QtGui.QApplication.UnicodeUTF8))
        self.srump1.setText(QtGui.QApplication.translate("rangeseldlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srmin.setToolTip(QtGui.QApplication.translate("rangeseldlg", "This is the lower bound of the range", None, QtGui.QApplication.UnicodeUTF8))
        self.srmax.setToolTip(QtGui.QApplication.translate("rangeseldlg", "This is the upper bound of the range.", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Contract ends of range by .1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp1.setText(QtGui.QApplication.translate("rangeseldlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rbmp5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Contract ends of range by .5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.rbmp5.setText(QtGui.QApplication.translate("rangeseldlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.rbpp1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Expand ends of range by .1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.rbpp1.setText(QtGui.QApplication.translate("rangeseldlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Expand ends of range by .1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp1.setText(QtGui.QApplication.translate("rangeseldlg", "+.1", None, QtGui.QApplication.UnicodeUTF8))
        self.rbpp5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Expand ends of range by .5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.rbpp5.setText(QtGui.QApplication.translate("rangeseldlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Expand ends of range by .5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbpp5.setText(QtGui.QApplication.translate("rangeseldlg", "+.5", None, QtGui.QApplication.UnicodeUTF8))
        self.rbmp1.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Contract ends of range by .1 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.rbmp1.setText(QtGui.QApplication.translate("rangeseldlg", "-.1", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp5.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Contract ends of range by .5 each side", None, QtGui.QApplication.UnicodeUTF8))
        self.srbmp5.setText(QtGui.QApplication.translate("rangeseldlg", "-.5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("rangeseldlg", "Both", None, QtGui.QApplication.UnicodeUTF8))
        self.datafiles.setToolTip(QtGui.QApplication.translate("rangeseldlg", "These are the spectra to be selected to compare ranges against", None, QtGui.QApplication.UnicodeUTF8))
        self.editrange.setToolTip(QtGui.QApplication.translate("rangeseldlg", "This is the range we want to edit", None, QtGui.QApplication.UnicodeUTF8))
        self.editrange.setItemText(0, QtGui.QApplication.translate("rangeseldlg", "(none)", None, QtGui.QApplication.UnicodeUTF8))
        self.selcolour.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Select colour on display", None, QtGui.QApplication.UnicodeUTF8))
        self.selcolour.setText(QtGui.QApplication.translate("rangeseldlg", "Choose Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("rangeseldlg", "Short Range Name", None, QtGui.QApplication.UnicodeUTF8))
        self.addnew.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Add a new range", None, QtGui.QApplication.UnicodeUTF8))
        self.addnew.setText(QtGui.QApplication.translate("rangeseldlg", "Add New", None, QtGui.QApplication.UnicodeUTF8))
        self.shortname.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Short name for the range", None, QtGui.QApplication.UnicodeUTF8))
        self.delrange.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Delete current range", None, QtGui.QApplication.UnicodeUTF8))
        self.delrange.setText(QtGui.QApplication.translate("rangeseldlg", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.selecty.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Whether we apply the Y range to plots", None, QtGui.QApplication.UnicodeUTF8))
        self.selecty.setText(QtGui.QApplication.translate("rangeseldlg", "Select Y Range", None, QtGui.QApplication.UnicodeUTF8))
        self.selectx.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Whether we apply the X range to plots", None, QtGui.QApplication.UnicodeUTF8))
        self.selectx.setText(QtGui.QApplication.translate("rangeseldlg", "Select X Range", None, QtGui.QApplication.UnicodeUTF8))
        self.rinuse.setToolTip(QtGui.QApplication.translate("rangeseldlg", "Range is in use", None, QtGui.QApplication.UnicodeUTF8))
        self.rinuse.setText(QtGui.QApplication.translate("rangeseldlg", "In use", None, QtGui.QApplication.UnicodeUTF8))

