# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sdadminmain.ui'
#
# Created: Wed Mar 19 11:03:51 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_sdadminmain(object):
    def setupUi(self, sdadminmain):
        sdadminmain.setObjectName("sdadminmain")
        sdadminmain.resize(400, 277)
        self.centralwidget = QtGui.QWidget(sdadminmain)
        self.centralwidget.setObjectName("centralwidget")
        sdadminmain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(sdadminmain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Data = QtGui.QMenu(self.menubar)
        self.menu_Data.setObjectName("menu_Data")
        sdadminmain.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(sdadminmain)
        self.statusbar.setObjectName("statusbar")
        sdadminmain.setStatusBar(self.statusbar)
        self.action_Source_directory = QtGui.QAction(sdadminmain)
        self.action_Source_directory.setObjectName("action_Source_directory")
        self.action_Tune_Ranges = QtGui.QAction(sdadminmain)
        self.action_Tune_Ranges.setObjectName("action_Tune_Ranges")
        self.action_Quit = QtGui.QAction(sdadminmain)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Peak_Comparison = QtGui.QAction(sdadminmain)
        self.action_Peak_Comparison.setObjectName("action_Peak_Comparison")
        self.action_Display_Results = QtGui.QAction(sdadminmain)
        self.action_Display_Results.setObjectName("action_Display_Results")
        self.action_Select_Observation_times_file = QtGui.QAction(sdadminmain)
        self.action_Select_Observation_times_file.setObjectName("action_Select_Observation_times_file")
        self.actionSpecify_spectral_data_format = QtGui.QAction(sdadminmain)
        self.actionSpecify_spectral_data_format.setObjectName("actionSpecify_spectral_data_format")
        self.action_Scaling_and_offsets = QtGui.QAction(sdadminmain)
        self.action_Scaling_and_offsets.setObjectName("action_Scaling_and_offsets")
        self.action_Save_Control = QtGui.QAction(sdadminmain)
        self.action_Save_Control.setObjectName("action_Save_Control")
        self.action_Save_Control_as = QtGui.QAction(sdadminmain)
        self.action_Save_Control_as.setObjectName("action_Save_Control_as")
        self.action_Select_Control_File = QtGui.QAction(sdadminmain)
        self.action_Select_Control_File.setObjectName("action_Select_Control_File")
        self.action_Select_Range_file = QtGui.QAction(sdadminmain)
        self.action_Select_Range_file.setObjectName("action_Select_Range_file")
        self.action_Save_ranges = QtGui.QAction(sdadminmain)
        self.action_Save_ranges.setObjectName("action_Save_ranges")
        self.action_Save_ranges_as = QtGui.QAction(sdadminmain)
        self.action_Save_ranges_as.setObjectName("action_Save_ranges_as")
        self.action_New_Control_File = QtGui.QAction(sdadminmain)
        self.action_New_Control_File.setObjectName("action_New_Control_File")
        self.action_New_range_file = QtGui.QAction(sdadminmain)
        self.action_New_range_file.setObjectName("action_New_range_file")
        self.menu_File.addAction(self.action_New_Control_File)
        self.menu_File.addAction(self.action_Select_Control_File)
        self.menu_File.addAction(self.action_Select_Observation_times_file)
        self.menu_File.addAction(self.action_Save_Control)
        self.menu_File.addAction(self.action_Save_Control_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_New_range_file)
        self.menu_File.addAction(self.action_Select_Range_file)
        self.menu_File.addAction(self.action_Save_ranges)
        self.menu_File.addAction(self.action_Save_ranges_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Data.addAction(self.action_Scaling_and_offsets)
        self.menu_Data.addAction(self.action_Tune_Ranges)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Data.menuAction())

        self.retranslateUi(sdadminmain)
        QtCore.QMetaObject.connectSlotsByName(sdadminmain)

    def retranslateUi(self, sdadminmain):
        sdadminmain.setWindowTitle(QtGui.QApplication.translate("sdadminmain", "Spectral data file admin", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("sdadminmain", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Data.setTitle(QtGui.QApplication.translate("sdadminmain", "&Data", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Source_directory.setText(QtGui.QApplication.translate("sdadminmain", "Source &Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Source_directory.setToolTip(QtGui.QApplication.translate("sdadminmain", "This selects the directory containing the spectral data.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Source_directory.setStatusTip(QtGui.QApplication.translate("sdadminmain", "This selects the directory containing the spectral data.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Source_directory.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Tune_Ranges.setText(QtGui.QApplication.translate("sdadminmain", "&Tune Ranges", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Tune_Ranges.setIconText(QtGui.QApplication.translate("sdadminmain", "Tune Ranges", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Tune_Ranges.setToolTip(QtGui.QApplication.translate("sdadminmain", "Adjust ranges in the range file.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Tune_Ranges.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("sdadminmain", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setStatusTip(QtGui.QApplication.translate("sdadminmain", "Quit program", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Peak_Comparison.setText(QtGui.QApplication.translate("sdadminmain", "&Calculate comparison", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Peak_Comparison.setStatusTip(QtGui.QApplication.translate("sdadminmain", "Run comparison procedure in batch", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Display_Results.setText(QtGui.QApplication.translate("sdadminmain", "Display &Results", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Display_Results.setToolTip(QtGui.QApplication.translate("sdadminmain", "Display Results of last comparison\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Select_Observation_times_file.setText(QtGui.QApplication.translate("sdadminmain", "Select &Observation times file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Select_Observation_times_file.setToolTip(QtGui.QApplication.translate("sdadminmain", "Select Observation times file, also select format of file.\n"
"The spectal data files are assumed to be in the same directory.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Select_Observation_times_file.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpecify_spectral_data_format.setText(QtGui.QApplication.translate("sdadminmain", "Specify &spectral data format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpecify_spectral_data_format.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Scaling_and_offsets.setText(QtGui.QApplication.translate("sdadminmain", "&Scaling and offsets", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Scaling_and_offsets.setShortcut(QtGui.QApplication.translate("sdadminmain", "Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_Control.setText(QtGui.QApplication.translate("sdadminmain", "&Save control", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_Control.setIconText(QtGui.QApplication.translate("sdadminmain", "Save control file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_Control.setToolTip(QtGui.QApplication.translate("sdadminmain", "Save control data to file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_Control.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_Control_as.setText(QtGui.QApplication.translate("sdadminmain", "Save control &as...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_Control_as.setToolTip(QtGui.QApplication.translate("sdadminmain", "Save control to specified file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_Control_as.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Select_Control_File.setText(QtGui.QApplication.translate("sdadminmain", "Select &Control File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Select_Control_File.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Select_Range_file.setText(QtGui.QApplication.translate("sdadminmain", "Select &Range file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_ranges.setText(QtGui.QApplication.translate("sdadminmain", "Save ranges", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_ranges.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_ranges_as.setText(QtGui.QApplication.translate("sdadminmain", "Save ranges as...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_ranges_as.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+Shift+G", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New_Control_File.setText(QtGui.QApplication.translate("sdadminmain", "&New Control File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New_Control_File.setToolTip(QtGui.QApplication.translate("sdadminmain", "Start new control file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New_Control_File.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New_range_file.setText(QtGui.QApplication.translate("sdadminmain", "New range file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New_range_file.setToolTip(QtGui.QApplication.translate("sdadminmain", "Staqrt a new range file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New_range_file.setShortcut(QtGui.QApplication.translate("sdadminmain", "Ctrl+Shift+N", None, QtGui.QApplication.UnicodeUTF8))

