#
# Generated Makefile for PyQt interfaces
#
# Created on Fri Aug 11 20:35:51 2017

PYUIC=pyuic5

all:	ui_gsedit.py \
	ui_geomdlg.py \
	ui_gseditdlg.py \
	ui_about.py

ui_gsedit.py:	gsedit.ui
	$(PYUIC) -o $@ $?

ui_geomdlg.py:	geomdlg.ui
	$(PYUIC) -o $@ $?

ui_gseditdlg.py:	gseditdlg.ui
	$(PYUIC) -o $@ $?

ui_about.py:	about.ui
	$(PYUIC) -o $@ $?

clean:
	rm -f ui_*.py *_rc.py *.pyc

distclean: clean

